### ISSUE TITLE
Add support for public-hostname

### ISSUE THREAD

**Issue by lcarva** [containerbuildsystem/osbs-box#58]
The `oc cluster up` command takes `--public-hostname` parameter. This is required when running a VM in a service like AWS, or OpenStack.

Let's add `--public-hostname` also to `osbs-box.py`.

**Comment by vrutkovs** [comment]
What if we add generic "--oc-params" to pass to `oc cluster up` (and `down` probably) instead? This would allow us to experiment with different setups without code change?

As for public hostnames support - I'm not sure if this is a good idea. `oc cluster up` was never designed to be outside of the dev machine (and I've seen Openshift folks resisting to add other networking opts there for this reason).

**Comment by lcarva** [comment]
`--oc-params` is a good idea. Maybe it can look something like:
```
osbs-box.py --oc-params public-hostname=blah.com
```

The public-hostname here is being used to make the OpenShift console available. Otherwise, it fails due to CORS restrictions.

**Comment by vrutkovs** [comment]
Sounds good to me

Would using `argparse.REMAINDER` help here - other parameters, not parsed by our script, would be used as `oc cluster <subcommand>`?

**Comment by lcarva** [comment]
Closing due to lack of interest and activity. If you're still interested feel free to reopen it.
