### ISSUE TITLE
Don't hard code 172.17.0.1

### ISSUE THREAD

**Issue by lcarva** [containerbuildsystem/osbs-box#63]
The value `172.17.0.1` is hard coded throughout the project. Although this works in most cases, it's not guaranteed.

The IP address refers to docker's bridge gateway. This is a nice way of accessing other services exposed in the host running the containers.

The actual value can be retrieved as:
```
docker network inspect -f "{{range .IPAM.Config }}{{ .Gateway }}{{end}}" bridge
```

`osbs-box.py` should compute this value and pass it in as a build arg when building `shared-data` and as a runtime parameter for `koji-client`.

**Comment by chmeliik** [comment]
This issue is obsolete (old version of osbs-box).
