### ISSUE TITLE
Add support for arrangement 6

### ISSUE THREAD

**Issue by lcarva** [containerbuildsystem/osbs-box#73]

**Comment by ktdreyer** [comment]
I see `reactor_config_map = reactor-config-map` in `openshift/configs/koji-builder-osbs.conf.j2`. Does that mean this is all done, or is there more work to do for Arrangement 6?

**Comment by MartinBasti** [comment]
Arrangement 6 is the only supported arrangement right now, maybe we will need just some cleanup.

**Comment by ktdreyer** [comment]
What sort of cleanup do we need?

**Comment by MartinBasti** [comment]
Probably just old unused configuration (which generates only deprecation warnings). I'm not sure I haven't investigated yet

**Comment by chmeliik** [comment]
This issue is obsolete (old version of osbs-box).
