### ISSUE TITLE
Make it easier to steal builds from other koji instances

### ISSUE THREAD

**Issue by lcarva** [containerbuildsystem/osbs-box#77]
The following can be used to take a koji build from a given koji instance and import it into the koji instance of osbs-box:

```bash
sudo docker exec -it osbsbox_koji-hub_1 \
  koji-steal-build  cockpit-0-5.f28container \
  --kojihub https://koji.fedoraproject.org/kojihub \
  --kojiroot https://kojipkgs.fedoraproject.org/
```

But to make the container image in the container registry used by osbs-box, you also need to run the following:
```bash
sudo ./osbs-box.py pull-image
  'candidate-registry.fedoraproject.org/f28/cockpit:0-5.f28container' \
  'f28/cockpit:0-5.f28container'
```

The metadata for the build however still points to the remote registry which doesn't really cause any problems AFAIK. It's just confusing.

`osbs-box.py` should provide a command the performs both operations above and update the build metadata to reference the container registry in osbs-box.

**Comment by lcarva** [comment]
`koji-steal-build` should also owner user of build if needed. `kojiadmin` user should also be granted content generator access:

```
docker exec -it osbsbox_koji-hub_1 koji grant_cg_access kojiadmin atomic-reactor
docker exec -it osbsbox_koji-hub_1 koji add-user $BUILD_OWNER
```

**Comment by chmeliik** [comment]
This issue is obsolete (old version of osbs-box).

Making it easier to steal builds would still be desirable, but it remains to be seen if osbs-box will still be useful after the OSBS redesign.
