### ISSUE TITLE
Investigate if koji-ssl-admin can be used

### ISSUE THREAD

**Issue by lcarva** [containerbuildsystem/osbs-box#88]
It might be worth looking to see if [koji-ssl-admin](https://pagure.io/koji-tools/pull-request/19) can be used instead of the hackish generate-certs scripts.

**Comment by ktdreyer** [comment]
Here is how I use it in my CI tests for [koji-ansible](https://github.com/ktdreyer/koji-ansible).

```bash
# Create SSL certs
git clone --depth 1 https://pagure.io/koji-tools.git

pushd koji-tools
./src/bin/koji-ssl-admin new-ca --common-name "travisci Koji CA"

# Create koji hub certificate:
./src/bin/koji-ssl-admin server-csr localhost
./src/bin/koji-ssl-admin sign localhost.csr

# Create koji user (client) certificate:
./src/bin/koji-ssl-admin user-csr travisci
./src/bin/koji-ssl-admin sign travisci.csr

# install client certs
mkdir -p ~/.koji/pki
cp koji-ca.crt ~/.koji/pki
cat travisci.crt travisci.key > travisci.cert
mv travisci.cert ~/.koji/pki/

# install hub certs
sudo cp koji-ca.crt /etc/ssl/certs/
cat localhost.crt koji-ca.crt | sudo tee /etc/ssl/certs/localhost.crt
cat localhost.crt koji-ca.crt | sudo tee /etc/ssl/certs/localhost.crt
sudo mv localhost.key /etc/ssl/private/localhost.key
sudo chown root:ssl-cert /etc/ssl/private/localhost.key
sudo chmod 640 /etc/ssl/private/localhost.key

popd  # koji-tools
```

**Comment by ktdreyer** [comment]
I'm using this in Ansible as well: https://github.com/ktdreyer/koji-playbooks/blob/master/roles/koji-ssl-admin/tasks/main.yml

**Comment by chmeliik** [comment]
FWIW, osbs-box now no longer uses a script for generating certificates, it now uses only ansible:
[tasks/generate-certs.yaml](../tree/master/tasks/generate-certs.yaml)
[tasks/generate-ownca-cert.yaml](../tree/master/tasks/generate-ownca-cert.yaml)

This has worked relatively well AFAIK, we might look at koji-ssl-admin  in the future if we encounter issues, but for now I'd keep what we have.

Thanks for the info though!

**Comment by lcarva** [comment]
Closing due to lack of interest and activity. If you're still interested feel free to reopen it.
